apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendations
  namespace: anime-api
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: recommendations
  template:
    metadata:
      labels:
        app: recommendations
    spec:
      serviceAccountName: anime-api-sa
      containers:
        - name: recommendations
          image: europe-west1-docker.pkg.dev/temp-488519/anime-repo/recommendations-bq:phase7-user-choice-ranked-progress
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: anime-api-config
          env:
            - name: RECOMMENDATIONS_MODE
              value: "smoke"
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            failureThreshold: 12
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 20
