# This file builds an environment that can run the recommendation system endpoint
    
# Get prebuilt image w/ python 3.10
FROM python:3.10

# Set working directory inside the container (equivalent to cd /app)
WORKDIR /app

# Copies requirements file from host to container
COPY requirements.txt .

# Installs python dependencies during build time
RUN pip install --no-cache-dir -r requirements.txt

# Pre-download LLM during docker build so as to not be internet dependent
RUN python -c "from sentence_transformers import SentenceTransformer; SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')"

# Copy all project files from host to container (/app)
COPY . .
    
# Start the API server when the container runs
#   Run FastAPI using Uvicorn:
#   app:app → app.py file, FastAPI instance named "app"
#   0.0.0.0 → listen on all network interfaces (allows external access)
#   8080 → internal container port
#   Automatically implements file changes (no need to restart api)
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]