#!/usr/bin/env bash
set -euo pipefail

DELIVERY_DIR="${DELIVERY_DIR:-phase8-delivery-antonio}"
IMAGE_PREFIX="${IMAGE_PREFIX:-phase7}"
IMAGE_TAG="${IMAGE_TAG:-ci}"
ANALYTICS_IMAGE="${IMAGE_PREFIX}-analytics:${IMAGE_TAG}"

rm -rf "${DELIVERY_DIR}"

mkdir -p "${DELIVERY_DIR}/images"
mkdir -p "${DELIVERY_DIR}/k8s"
mkdir -p "${DELIVERY_DIR}/scripts"
mkdir -p "${DELIVERY_DIR}/tests"
mkdir -p "${DELIVERY_DIR}/workflow"
mkdir -p "${DELIVERY_DIR}/phase_7"

echo "Saving analytics Docker image: ${ANALYTICS_IMAGE}"
docker save "${ANALYTICS_IMAGE}" -o "${DELIVERY_DIR}/images/phase7-analytics-ci.tar"

cp -r phase_7/k8s "${DELIVERY_DIR}/k8s/phase_7"
cp -r phase_7/analytics "${DELIVERY_DIR}/phase_7/"
cp -r phase_7/recommendations "${DELIVERY_DIR}/phase_7/"
cp -r tests/phase_7 "${DELIVERY_DIR}/tests/"
cp scripts/run-local-tests.sh "${DELIVERY_DIR}/scripts/"
cp scripts/build-phase7-images.sh "${DELIVERY_DIR}/scripts/"
cp .github/workflows/ci.yml "${DELIVERY_DIR}/workflow/"
cp requirements-test.txt pytest.ini "${DELIVERY_DIR}/"

cat > "${DELIVERY_DIR}/release-metadata.txt" <<METADATA_EOF
Phase 8 Continuous Delivery Artifact
Generated at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
Git commit: $(git rev-parse HEAD)
Git branch: $(git rev-parse --abbrev-ref HEAD)
Analytics image: ${ANALYTICS_IMAGE}
Image tar: images/phase7-analytics-ci.tar
METADATA_EOF

cat > "${DELIVERY_DIR}/README.md" <<'README_EOF'
# Phase 8 Continuous Delivery Artifact

This artifact was generated by the CI/CD pipeline after the validation jobs passed.

It contains:

- A saved analytics Docker image tar file.
- Kubernetes and Istio manifests.
- The CI workflow file.
- Local test and build scripts.
- Test configuration and test files.
- The Phase 7 analytics and recommendations source folders used by the tests.

## Load the Docker image

```bash
docker load -i images/phase7-analytics-ci.tar
```

## Run tests from the repository

```bash
bash scripts/run-local-tests.sh
```

## Deployment note

This is a Continuous Delivery artifact. It is prepared for deployment but is not automatically deployed to GKE.
A future deployment step could push the image to Artifact Registry and apply the manifests to a GKE cluster.
README_EOF

find "${DELIVERY_DIR}" -type d -name "__pycache__" -prune -exec rm -rf {} +
find "${DELIVERY_DIR}" -type d -name ".pytest_cache" -prune -exec rm -rf {} +
find "${DELIVERY_DIR}" -type f -name "*.pyc" -delete

echo "Delivery artifact prepared in ${DELIVERY_DIR}"