apiVersion: v1
kind: ConfigMap
metadata:
  name: anime-api-config
  namespace: anime-api
data:
  GCP_PROJECT_ID: "temp-488519"
  BQ_DATASET: "anime_intel_dataset"
  BQ_TABLE: "anime_intel"
  ANALYTICS_SERVICE_URL: "http://analytics.anime-api.svc.cluster.local"
  ANALYTICS_TIMEOUT_SECONDS: "3"
  INDEX_BATCH_SIZE: "256"
